




.build/uno/src/pixymaster.cpp : src/pixymaster.ino
	@mkdir -p .build/uno/src
	@echo [93msrc/pixymaster.ino[0m
	@/usr/local/bin/ino preproc  -o $@ $^


all : .build/uno/src/pixymaster.cpp
	@true

